### ISSUE TITLE
Executar o Guia do Maven no Spring

### ISSUE THREAD

**Issue by Lu1sLima** [Lu1sPROG/Dell-IT#1]

**Comment by Lu1sLima** [comment]
Guia no site da Spring:

https://spring.io/guides/gs/maven/

![image](https://user-images.githubusercontent.com/50342687/66507519-b6452900-eaa5-11e9-815f-423614c0e63b.png)

**Comment by Lu1sPROG** [comment]
Esse é o site:

![image](https://user-images.githubusercontent.com/50342687/66507469-a2012c00-eaa5-11e9-870f-57213d5c1389.png)

**Comment by Lu1sLima** [comment]
Dar um clone no repositório:
![image](https://user-images.githubusercontent.com/50342687/66507986-9cf0ac80-eaa6-11e9-80c1-45e2ec41ae18.png)

**Comment by Lu1sLima** [comment]
Clonando pasta localmente no Bash:
![image](https://user-images.githubusercontent.com/50342687/66508238-0bce0580-eaa7-11e9-8b5a-11333acb40d5.png)

cd dell-it

**Comment by Lu1sLima** [comment]
Tudo OK:
![image](https://user-images.githubusercontent.com/50342687/66508395-66676180-eaa7-11e9-9ea4-de32d41a0e68.png)
